# Generated by Django 4.1 on 2023-05-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_ordermodel_estate_alter_ordermodel_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='town',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
